# Numpy Basics

In [5]:
import numpy as np

In [7]:
np_arr=np.array([2,4,3,4,5,7,8])
np_arr

array([2, 4, 3, 4, 5, 7, 8])

In [9]:
type (np_arr)

numpy.ndarray

# Diffrence between list and ndArray

In [10]:
list1=['pizza','topings','dominos']

In [12]:
list2=list1*2
list2

['pizza', 'topings', 'dominos', 'pizza', 'topings', 'dominos']

In [17]:
pyList=[1,2,3,4,5,6]
pyList*2

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [15]:
np_arr=np.array([2,4,3,5,7,8])
np_arr*2

array([ 4,  8,  6, 10, 14, 16])

In [18]:
pyList1=pyList+pyList
pyList1

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [21]:
np_arr2=np_arr+np_arr
print(np_arr)
np_arr2

[2 4 3 5 7 8]


array([ 4,  8,  6, 10, 14, 16])

# Some Numpy Attributes

In [28]:
np_arr1=np.array([(2,3,4,5),(4,5,6,7)],dtype=float)
print(np_arr1)
type(np_arr1)

[[2. 3. 4. 5.]
 [4. 5. 6. 7.]]


numpy.ndarray

In [30]:
np_arr1=np.array([(2,3,4,5),(4,5,6,7)],dtype=complex)
print(np_arr1)
type(np_arr1)

[[2.+0.j 3.+0.j 4.+0.j 5.+0.j]
 [4.+0.j 5.+0.j 6.+0.j 7.+0.j]]


numpy.ndarray

In [32]:
#second method to generate array
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
#third method to create array
np.linspace(5,10,5,dtype=float)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [39]:
np.linspace(5,10,dtype=float)

array([ 5.        ,  5.10204082,  5.20408163,  5.30612245,  5.40816327,
        5.51020408,  5.6122449 ,  5.71428571,  5.81632653,  5.91836735,
        6.02040816,  6.12244898,  6.2244898 ,  6.32653061,  6.42857143,
        6.53061224,  6.63265306,  6.73469388,  6.83673469,  6.93877551,
        7.04081633,  7.14285714,  7.24489796,  7.34693878,  7.44897959,
        7.55102041,  7.65306122,  7.75510204,  7.85714286,  7.95918367,
        8.06122449,  8.16326531,  8.26530612,  8.36734694,  8.46938776,
        8.57142857,  8.67346939,  8.7755102 ,  8.87755102,  8.97959184,
        9.08163265,  9.18367347,  9.28571429,  9.3877551 ,  9.48979592,
        9.59183673,  9.69387755,  9.79591837,  9.89795918, 10.        ])

In [41]:
np.linspace(1,10,num=10,dtype=float)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [43]:
np.linspace(1,10,num=10,endpoint=False,dtype=float)

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [ ]:
np.arange(1,9)reshape

In [44]:
np.zeros((1,3))

array([[0., 0., 0.]])

In [45]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
#identical matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
np.random.rand(1,10)

array([[0.45181642, 0.67736514, 0.3376088 , 0.63211262, 0.85965107,
        0.23696204, 0.18824997, 0.07221463, 0.44001718, 0.75925999]])

In [68]:
arr_num=np.random.random((3,5))
arr_num

array([[0.00824929, 0.86138016, 0.35658565, 0.51244619, 0.99308841],
       [0.4969456 , 0.90014798, 0.87981298, 0.96462669, 0.00167665],
       [0.60113927, 0.02036841, 0.0215031 , 0.69762957, 0.18617738]])

In [69]:
#list slicing
list3=[1,2,3,4,5,6]
print(list3[1:3])
print(list3[:2])
print(list3[:])
print(list3[1:])

[2, 3]
[1, 2]
[1, 2, 3, 4, 5, 6]
[2, 3, 4, 5, 6]


In [74]:
arr4=np.random.random((3,4))
arr4
arr4[1:4,1:4]

array([[0.20474979, 0.80855316, 0.58121479],
       [0.91610261, 0.44036165, 0.12372615]])

# Broadcasting

In [83]:
np_val=np.arange(1,10)
print(np_val)
np_val.shape

[1 2 3 4 5 6 7 8 9]


(9,)

In [82]:
np_val1=np.ones(7)
print(np_val1)
np_val1.shape

[1. 1. 1. 1. 1. 1. 1.]


(7,)

In [78]:
np_val+np_val1
#error bcoz they are of diffrent shape

ValueError: operands could not be broadcast together with shapes (9,) (7,) 

In [80]:
new_np_val=np_val.reshape(9,1)
new_np_val

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [81]:
new_np_val+np_val1

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.],
       [10., 10., 10., 10., 10., 10., 10.]])

In [84]:
new_np_val*np_val1

array([[1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9.]])